// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJcOsWle-mQkXiuEM8-kRDRFJqFYdBJRA',
    appId: '1:28249573641:web:edffb0d1ec4bfa64c5ebd8',
    messagingSenderId: '28249573641',
    projectId: 'ulearning-app-fc393',
    authDomain: 'ulearning-app-fc393.firebaseapp.com',
    storageBucket: 'ulearning-app-fc393.appspot.com',
    measurementId: 'G-78EEC3C1RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpdsLT7cOBTPBTiHhPg-aTx3Jjzdny-H0',
    appId: '1:28249573641:android:8c7fed4676f3a193c5ebd8',
    messagingSenderId: '28249573641',
    projectId: 'ulearning-app-fc393',
    storageBucket: 'ulearning-app-fc393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_rWrKOME_6wRfAk3Lq7ptTX8dEHdwzXw',
    appId: '1:28249573641:ios:9eacd77639ba64a2c5ebd8',
    messagingSenderId: '28249573641',
    projectId: 'ulearning-app-fc393',
    storageBucket: 'ulearning-app-fc393.appspot.com',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_rWrKOME_6wRfAk3Lq7ptTX8dEHdwzXw',
    appId: '1:28249573641:ios:198f5e86200bb4adc5ebd8',
    messagingSenderId: '28249573641',
    projectId: 'ulearning-app-fc393',
    storageBucket: 'ulearning-app-fc393.appspot.com',
    iosBundleId: 'com.example.ulearningApp.RunnerTests',
  );
}
